### ISSUE TITLE
Get Master, Worker pages fully ported

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#1001]
[Story](https://www.pivotaltracker.com/story/show/96348194)
[Parent Issue](https://github.com/intel-hadoop/gearpump/issues/952)

Master and Worker pages should look like original including runtime REST requests

**Comment by kkasravi** [comment]
Additionally a fix has been made so that when ~fastOptJS detects that a scala file has been modified it copies it to the output directory so that the browser is updated on refresh. Prior to this a script was required to do this.

**Comment by clockfly** [comment]
merge into parent issue #952
