### ISSUE TITLE
Dynamic DAG

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#101]
After a client submit's an AppDescription, the client should be able to modify the DAG by adding or removing nodes which then results in the AppMaster updating the workers, executors with this information. Details such as what happens to currently running tasks and how new tasks are added should be covered here within a design doc. Additional details should also be covered:
1. Whether tasks can be removed and resulting behaviors. 
2. Whether the partitioner can be replaced or modified.
3. Whether existing task parallelism hints can be updated.

Task list:

- [x] pre-calculate the dependencies information in AppMaster, and push the subscription info to tasks.
- [x] ClockService allow to add or remove a processor.
- [x] Add dynamic subscribe/unsubscribe interface to TaskActor
- [x] Handle message loss
- [ ] UI support dynamic dag update
- [x] Allow DAG modification by config file. 
- [x] multiple version DAG
- [x] akka user interface for dag udpate
- [x] rest api for dag upate.
- [x] multiple version tasks
- [x] task manager state transition during dyanmic dag
- [x] unique reprenstation of dag
- [x] refactor task scheduler to remove dependencies on DAG.
- [x] refactor task scheduler to handle dynamic DAG change.
- [x] Add DAGManager to manage the DAG change
- [x] Allow dynamically change resource used by an executor.

**Comment by clockfly** [comment]
Task list:

- [ ] pre-calculate the dependencies information in AppMaster, and push the subscription info to tasks.
- [ ] ClockService allow to add or remove a processor.
- [ ] Add dynamic subscribe/unsubscribe interface to TaskActor
- [ ] Handle message loss

**Comment by clockfly** [comment]
### Dynamic DAG Summary:

Dynamic DAG is a feature which allows you to change the runtime DAG in the fly. Without disrupting the application.

The goal of dynamic dag is:
1. smooth upgrade. No message loss.
2. In the transition process of dynamic DAG, we can remain the "exactly once" message processing feature.
3. Automatically fall-back to old DAG, when upgrading failed.

With dynamic DAG, we can:
1. Update only certain part of the DAG, without disrupting service.
2. Change the task parallism dynamically with no message loss.
3. Change configuration of task dynamically.
4. Add new data source to exsting runtime DAG.
5. Add new sink to existing DAG, like writing a extra copy to HDFS.
6. Create temporary processors to existing DAG, to inspect the application status.

**Comment by clockfly** [comment]
The last UI task is covered by #1156
