### ISSUE TITLE
Gearpump Connector Framework

### ISSUE THREAD

**Issue by whjiang** [intel-hadoop/gearpump#1012]
# [Story](https://www.pivotaltracker.com/story/show/96641634)
# Goal
The goal of connector is to make an easy-to-extend and easy-to-use Connector (DataSource and DataSink) system.

# How do Spark Streaming and Flink model this?
For Spark Streaming, [Input DStreamings](https://spark.apache.org/docs/latest/streaming-programming-guide.html#input-dstreams-and-receivers) and [Receiver](https://spark.apache.org/docs/latest/streaming-custom-receivers.html) for general Receiver API.

For Flink, [SourceFunction](http://ci.apache.org/projects/flink/flink-docs-release-0.8/streaming_guide.html#sources).

Both Spark Streaming and Flink model the connectors in a highly identical way. 

## DataSource
Basically, they both modeled in this way:

1. A DataSource (Spark named it as ```InputDStream``` or  ```Receiver``` and Flinked as ```SourceFunction```) generates a stream of type T (T is the decoded message type). So, it means decoding of message is the duty of DataSource. 
   1. DataSource has Start, Stop, Restart events to handle to ensure it is correct even when fault tolerant. 
2. Categorize common-used DataSources into two categories:
   1. Basic sources (not depending on another service), e.g. file system watcher, socket,  akka actor, collection, sequence. These sources have been builtin support in StreamingContext for creation. E.g. 
   ```  streamingContext.fileStream[KeyClass, ValueClass, InputFormatClass](dataDirectory)```
   2. Advanced sources (depending on other service), e.g. Kafka, Flume, .... these sources are provided via some util classes. E.g. 
   ```TwitterUtils.createStream(ssc, None)```

So, it means that for DataSource, the framework is DataSource agnostic. User specify DataSource via either predefined data sources (e.g. File system watche) or provided his own implementation of DataSource by implementing ```Receiver``` or ```SourceFunction```. The configuration of DataSource is not part of the application. E.g. for Kafka, the creation of data source in Spark Streaming is:

```
 import org.apache.spark.streaming.kafka._

 val kafkaStream = KafkaUtils.createStream(streamingContext, 
     [ZK quorum], [consumer group id], [per-topic number of Kafka partitions to consume])
```

## DataSink
For DataSink, Flink named as ```DataStreamSink``` or ```SinkFunction``` while Spark Streaming just named it as "Output Operations". But, basically, they are the same. The model is:

1. Provide a general mechanism for Sink. For Spark, it is ```foreachRDD``` function. For Flink, it is ```SinkFunction```. User implemented this function can do whatever output they want.
2. Provide builtin support for simple output, e.g. ```print```, ```saveAsTextFiles```, ```saveAsObjectFiles```, ```saveAsHadoopFiles```, ```writeAsCsv```. 

It is obvious that DataSink follows the same convention as DataSource.

## Package organization
As connectors (especially the connectors depending on external services, e.g. Kafka) are part of application instead of streaming framework, Spark put corresponding connectors under different artifact. E.g. kafka connector (both DataSource and DataSink) is in a standalone artifact ```spark-streaming-kafka_2.10```. 

Typically, each such artifact contains one DataSource and one DataSink. There are exceptions to this. E.g. Twitter connector only has DataSource. 

# Gearpump Design
We will follow the best practices from Spark Streaming and Flink if possible. 

### DataSource
We will provide a ```DataSource``` as the base class for data input stream. The signature looks like

``` abstract class DataSource[T](taskContext, userConf) extends Task(taskContext, userConf)```
```T``` is the message type.

And we will provide built-in implementation for common usages like, file system watch and Kafka.... 

The desired Kafka source shall be used in following way:

```
 import org.apache.gearpump.streaming.kafka._

 val KafkaStream = KafkaSource([ZK quorum], [consumer group id], [per-topic number of Kafka partitions to consume])
```

```kafkaSource``` is implemented in this way:

```
   object KafkaSource extends Processor[KafkaSourceTask] {
   		def apply([ZK quorum], [consumer group id], [per-topic number of Kafka partitions to consume]) {
   		    //put these arguments into taskConf
   		    ...
   		}
   }
```

### DataSink

We will provide a ```DataSink``` as the base class for data sink. The signature looks like

``` abstract class DataSink(taskContext, userConf) extends Task(taskContext, userConf)```

And we will provide built-in implementation for common usages like, file write and HBase.... 

The desired HBase sink shall be used in following way:

```
 import org.apache.gearpump.streaming.hbase._

 val hbaseSink = HBaseSink(hbaseConf)
```

```HBaseSink``` is implemented in this way:

```
   object HBaseSink extends Processor[HBaseSinkTask] {
   		def apply(hbaseConf) {
   		    //put hbaseConf into taskConf
   		    ...
   		}
   }
```

## High level API
TBD

**Comment by manuzhang** [comment]
I can refactor the kafka module to conform to this design as first try.

**Comment by kkasravi** [comment]
Sure, though let me move some of the DSL types that are related under external. I'll open a sub task for this

**Comment by clockfly** [comment]
Seems this feature is implemented.

Close this.
