### ISSUE TITLE
Move kafka, hbase and some supporting types in experiments/dsl to extern

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#1015]
[Story](https://www.pivotaltracker.com/story/show/96641634)
[Parent Issue](https://github.com/intel-hadoop/gearpump/issues/1012) 

See [Gearpump Connector Framework on Git](https://github.com/intel-hadoop/gearpump/issues/1012)
Initial task that is a prerequisite for subsequent Connector work

**Comment by clockfly** [comment]
fixed by https://github.com/intel-hadoop/gearpump/pull/1089
