### ISSUE TITLE
Port tabset.js

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#1016]
[Story](https://www.pivotaltracker.com/story/show/96348194)
[Parent Issue](https://github.com/intel-hadoop/gearpump/issues/952)
See [scalajs-ionic-starttabs](https://github.com/olivergg/scalajs-ionic-starttabs) and [angular-ui-router](http://www.michaelbromley.co.uk/blog/100/auto-breadcrumbs-with-angular-ui-router)

**Comment by clockfly** [comment]
merge into parent issue #952

**Comment by clockfly** [comment]
merge into parent issue #952
