### ISSUE TITLE
import twitter chill library for kryo serialization

### ISSUE THREAD

**Issue by manuzhang** [intel-hadoop/gearpump#1019]
> [Chill](https://github.com/twitter/chill) is extensions for the Kryo serialization library including serializers and a set of classes to ease configuration of Kryo in systems like Hadoop, Storm, Akka, etc.

Chill-Scala provides support for singletons, scala Objects and the following types:

* Scala primitives
  * scala.Enumeration values
  * scala.Symbol
  * scala.reflect.Manifest
  * scala.reflect.ClassManifest
  * scala.Function[0-22] closure cleaning (removing unused `$outer` references).
* Collections and sequences
  * scala.collection.immutable.Map
  * scala.collection.immutable.List
  * scala.collection.immutable.Vector
  * scala.collection.immutable.Set
  * scala.collection.mutable.{Map, Set, Buffer, WrappedArray}
  * all 22 scala tuples

By bringing in chill, users will get serialization for commonly used types for free. 

We've already used chill's `KryoInjection` in state module to convert between `Any` and `Array[Byte]`. (Note `Any` here means all types supported and registered by chill and kryo)

**Comment by clockfly** [comment]
There is already serializer by class in this list. 

It is covered by aka-kryo-serializer.
