### ISSUE TITLE
Many timeout related UT failures

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#1027]
[Story](https://www.pivotaltracker.com/story/show/95597796)
[Parent Issue](https://github.com/intel-hadoop/gearpump/issues/970)
See follow up comments of various Travis build failures

**Comment by clockfly** [comment]
fixed by https://github.com/intel-hadoop/gearpump/pull/1164

**Comment by clockfly** [comment]
duplicate of #1165
