### ISSUE TITLE
replace ngRoute and ng-breadcrumbs with scalajs UIRouter extension

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#1033]
[Story](https://www.pivotaltracker.com/story/show/96956046)
[Parent Issue](https://github.com/intel-hadoop/gearpump/issues/952)
See [UIRouter.scala](https://github.com/greencatsoft/scalajs-angular/blob/master/src/main/scala/com/greencatsoft/angularjs/extensions/UIRouter.scala) and [angular-ui-router](http://www.michaelbromley.co.uk/blog/100/auto-breadcrumbs-with-angular-ui-router)

**Comment by clockfly** [comment]
merge into parent issue #952
