### ISSUE TITLE
remove logs when cluster is running,but program won't create again

### ISSUE THREAD

**Issue by clarencezi** [intel-hadoop/gearpump#1037]
I remove gearpump master,ui or worker log in logs directory, but program would not do as kafka logs, it won't create the log file again and append

**Comment by skw1992** [comment]
Could you let me know whether you removed the whole 'logs' folder or just removed some log files in the 'logs' folder?

**Comment by clarencezi** [comment]
I just removed some log files in the 'logs' folder
