### ISSUE TITLE
Fix NotSerializableException when fetching workers

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#1040]
[Story](https://www.pivotaltracker.com/story/show/96956046)
[Parent Issue](https://github.com/intel-hadoop/gearpump/issues/952)
Getting java.io.NotSerializableException: scala.collection.MapLike$$anon$2 and a 500 internal server error

**Comment by kkasravi** [comment]
Make sure unit tests also test this error condition

**Comment by clockfly** [comment]
Where is the PR?

**Comment by kkasravi** [comment]
This is part of #952 - scalajs branch has the fix

**Comment by clockfly** [comment]
OK.
Close this as #952 contains this one.
