### ISSUE TITLE
Add Processor object at runtime

### ISSUE THREAD

**Issue by whjiang** [intel-hadoop/gearpump#1051]
Currently, Processor is a pure client side concept. The corresponding object at runtime is Task. At runtime, we don't have Processor object at runtime.

This makes the coding a little weird. E.g. in #1049, client set configuration in DataSinkProcessor. But, at runime, DataSinkTask read out this configuration. So, the configuration read/write is done in two classes. 
```
object DataSinkProcessor {
  def apply(dataSink: DataSink,
            parallelism: Int,
            description: String = "",
            taskConf: UserConfig = UserConfig.empty)(implicit system: ActorSystem): Processor[DataSinkTask] = {
    Processor[DataSinkTask](parallelism, description = description,
      taskConf.withValue[DataSink](DataSinkTask.DATA_SINK, dataSink))
  }
}
```
And
```
class DataSinkTask (context: TaskContext, conf: UserConfig) extends Task(context, conf) {  
  private val sink = conf.getValue[DataSink](DATA_SINK).get  
}
```

A better solution is to support Processor object at runtime. Task can get its processor by 
```
taskContext.getProcessor.getXXXConf
```
In this way, we can make the code organized better.

And I also believe a runtime Processor object can hold more info than conf which will benefit runtime task management, though I don't have any concrete example.

**Comment by whjiang** [comment]
And also this can help clarify several concepts. E.g. at runtime, we have TaskConfig, is it different for different tasks in the same processor?

**Comment by manuzhang** [comment]
I'd say `Processor` belongs to DAG, a logical plan while `Task` is a runtime instance of physical plan. We'd better not mix the two.

**Comment by whjiang** [comment]
@manuzhang my guesstion is to make Task, at runtime, able to get info about its Processor.

**Comment by kkasravi** [comment]
Certain metadata held in the logical plan should be available in the physical plan. Both logical and physical might even share certain traits. Worth reviewing IMO

**Comment by clockfly** [comment]
-1

Reason:
1. TaskContext already contains many information, like paraliism, description, which is Processor provides.
2. Some Processor field like taskclass is not useful for Task implementation.
3. Some field will be changed when passing to runtime, like taskConf. It will merge with worker config.
4.  It is risky to serialize user defined Processor and pass them to tasks. As we don't know what fields user's Processor may define.
