### ISSUE TITLE
Add unit tests for org.apache.gearpump.dashboard.controllers.StreamingDag

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#1058]
[Story](https://www.pivotaltracker.com/story/show/96956046)
[Parent Issue](https://github.com/intel-hadoop/gearpump/issues/952)
StreamingDag processing of StreamingAppMasterDataDetail needs to be verified using a fixed StreamingAppMasterDataDetail

**Comment by clockfly** [comment]
merge into parent issue #952
