### ISSUE TITLE
external/kafka module should support pull data from kafka with the original type bytes

### ISSUE THREAD

**Issue by clarencezi** [intel-hadoop/gearpump#1060]
Question：the method pull(number: Int) in KafkaSource.scala use"messageDecoder.fromBytes(kafkaMsg.msg)" to change Array[Byte] to String, but in our project we need the  type Array[Byte],  otherwise after "fromBytes(kafkaMsg.msg)" the original data would be changed.
And here is what i do： 
in order not to change the pull(num: Int) method in trait TimeReplayableSource, 
I just change the method pull(number: Int) in KafkaSource.scala, here is the code：  
"val msg = if(KafkaConstants.CHOOSE_BYTE) Message(kafkaMsg.msg, System.currentTimeMillis()) else messageDecoder.fromBytes(kafkaMsg.msg)"

explain：KafkaConstants.CHOOSE_BYTE is the Boolean type, we can change this value in method onStart(newStartTime: StartTime) in KafkaSpout.scala to suit 
my project
I hope gearpump can support this situation.

**Comment by manuzhang** [comment]
Thanks for reporting the issue. I've opened #1063 to keep the bytes type. Actually,  `MessageDecoder` is an interface and you can use whatever decoder you like by configuring `kafka.task.message.decoder.class` in `kafka.conf`.

**Comment by clockfly** [comment]
Thanks for reporting.
PR https://github.com/intel-hadoop/gearpump/pull/1063/files
is merged.
