### ISSUE TITLE
Gearpump multitenancy in context of security

### ISSUE THREAD

**Issue by TomaszT** [intel-hadoop/gearpump#1069]
[Story](https://www.pivotaltracker.com/story/show/98067328)
Two or more organizations can use GP deployed on the same Yarn Kerberized cluster in secure way. (in simple model, organizations are group of users, that has the same access rights)

**How GP should achieve this**

I think that GP should go with Hadoop’s security mechanisms. So we could address above problem with Kerberos, ACLs + Sentry compatibility. 

**Requirements**

User from one organization can’t access other organization’s apps/data. (Details are described in related issues.)

**Comment by clockfly** [comment]
merge this into parent issue. #1247
