### ISSUE TITLE
Kill application doesn't work through YARN proxy

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#1086]
[Story](https://www.pivotaltracker.com/story/show/98129134)
YARN proxy will not forward http DELETE

**Comment by clockfly** [comment]
Use redirect instead.

**Comment by kkasravi** [comment]
We will resolve this issue using a proxy rather than attempt to do everything through the YARN web console which returns a 405 for every HTTP method except GET. However we should return an appropriate error page in the UI
