### ISSUE TITLE
Unable to submit application to master

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#1117]
[Story](https://www.pivotaltracker.com/story/show/98427104)
Non-compatible change to sbt-pack which now uses JAVA_OPTS instead of JVM_OPT between version 0.6.12 and 0.7.4. This prevented export JVM_OPT=-Dgearpump.cluster.masters.0=${MASTER} -Dgearpump.hostname=$(hostname) from working in linux bash scripts

**Comment by clockfly** [comment]
I think this is in your local script. Not gearpump directly related.
