### ISSUE TITLE
scale up to 10, 000 tasks on single four-core machine

### ISSUE THREAD

**Issue by clockfly** [intel-hadoop/gearpump#1151]
In theory, with effecitve flow control, we should be able to scale to as many tasks as we want.

But in reality, it depends on:
1. memory footprint of single task is small enough, so that there is no out of memory.
2. GC pause interval is still under control to avoid remote watching timeout.

**Comment by manuzhang** [comment]
@clockfly 

I'm trying to carry out experiment in a local cluster with wordcount (1000 splits, 1000 sums) but `AppMaster` failed to allocate resource after timeout.

I've changed the following configs 

```
gearpump.worker-slots=1000000
gearpump.resource.allocation-timeout-seconds=600
```

my machine is 4 cores with 2.5 GB free memory.

**Comment by clockfly** [comment]
It woks fine for 2000 tasks on my laptop.

Have you restarted the local daemon?

**Comment by clockfly** [comment]
As we maintain  a sliding window for every task-to-task connection.
The overall memory consumption is significant.

For example,
For 10, 000 task  shuffle to another 10, 000 task, there will be 100M sliding window. If we use 60 bytes for each sliding window, it will take 6GB memory space.

If we can reduce the overhead per sliding window to 15 bytes, then overall head will be reduced by 25%, 1.5GB. 

Thoughts:
1. Use primitive map. 
2. Use short instead of Long for flow control.
3. Optimize the min Clock algorithm. Avoid the cost of storing clock values.
4. Another optimization will be create intermediate processor layer. That will turn 10, 000 - 10, 0000 shuffle, to 
e.g. 10, 000 -> 100 -> 10.000, then the sliding window count will be 2M. The overall memory consumption will be 120MB(60 bytes per sliding window). But these will not be application transparent.

**Comment by clockfly** [comment]
For each sliding window, now we reduce the memory footprint from 100 bytes to 35 bytes.

But it is still not optimal.

**Comment by clockfly** [comment]
For a 2GB memory machine, we can at most support 8000 task shuffle to another 8000 tasks.

In these 35 bytes. 
1. 13 bytes used to store the received message count. (In theory, we only need 6 bytes, with 4 bytes as key, and 2 bytes as value. But as it is a hashmap, 2x the space will be used.)
2. 8 bytes to store the min-clock for current sliding window.
3. 8 bytes to store the candidate min-clock for current sliding window.
4. 2 byte to store sent message count.
5. 2 byte to store pending message count.
6. 2 bytes to store threshold message count. (the sent message > threshold, then candidate clock is effective).

There maybe some room in 1, 2. 3. It may be possible to reduce 35 bytes to 14 bytes. Then in theory, for 2GB memory, we can support 12000 tasks shuffle to another 12000 tasks.
