### ISSUE TITLE
Self contained jar applications should be able to specify arguments

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#1154]
[Story](https://www.pivotaltracker.com/story/show/98673918)
Loading client applications via REST as jar files should provide a way to specify command line args and conf files

**Comment by clockfly** [comment]
Besides jar, we should also allow user to specify:
1. MainClass [optional]. If not specified, we will use the default MainClass in manifest.in
2. Command line arguments.

**Comment by stanleyxu2005** [comment]
The feature is nearly done. But I am thinking to split upload and launch in two apis. There are two reasons:
1. Upload once, launch with arguments you want. You can save bandwidth to upload repeatedly.
2. For security intensive usage, maybe only admin is privileged to deploy application. User/operator is only allowed to run application.

**Comment by kkasravi** [comment]
There should be 2 APIs - we will need to surface a catalog of available apps in next demo...

**Comment by clockfly** [comment]
the PR not working.

For example, when choose wordcount.jar, and use paramter
-split 2 -sum 1
