### ISSUE TITLE
[Dynamic DAG] Add UI for dynamic DAG.

### ISSUE THREAD

**Issue by clockfly** [intel-hadoop/gearpump#1156]
We allow user to replace a processor.
UI fields:
1. oldProcessorId
2. new Name
3. new Parallism.
4. new Task Class Name.

**Comment by stanleyxu2005** [comment]
From the unittest, I see a way to add new processors (including edges). So if you want to modify a dag, you should provide the whole dag body (including all processors and all edges), right?

**Comment by kkasravi** [comment]
Here are the related definitions for scalajs. We probably want a way to manipulate the graph on both client and server - so a scalajs based graph that has no dependencies. It would be interesting to see if org.grapht.Graph can be converted to JS via scalajs. I have not done this exercise.

```
  case class StreamingAppMasterDataDetail(
      appId: Int,
      appName: String = null,
      actorPath: String = null,
      clock: String = null,
      executors: Map[ExecutorId, String] = null,
      tasks: Map[TaskId, ExecutorId] = null,
      processors: Map[ProcessorId, ProcessorDescription] = null,
      processorLevels: Map[ProcessorId, Int] = null,
      dag: Dag = null
  ) extends AppMasterDataDetail
```

```
  case class ProcessorDescription(id: ProcessorId, taskClass: String, parallelism : Int, description: String = "")
  case class Dag(vertices: Seq[Int], edges: Seq[(Int, String, Int)])
````

StreamingDag API is below
![screen shot 2015-07-17 at 3 07 49 am](https://cloud.githubusercontent.com/assets/146453/8745099/2bbb2dd4-2c31-11e5-8693-856a5f318d18.png)
