### ISSUE TITLE
Get appprocessor.html working with data

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#1172]
[Story](https://www.pivotaltracker.com/story/show/98877146)
[Parent Issue](https://github.com/intel-hadoop/gearpump/issues/952)
Complete port of AppProcessorCtrl.scala and AppProcessorChartsCtrl.scala

**Comment by clockfly** [comment]
merged into parent https://github.com/intel-hadoop/gearpump/issues/952
