### ISSUE TITLE
Enable nightly snapshots to be published to sonatype

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#1214]
[Story](https://www.pivotaltracker.com/story/show/99850806)
Developers creating apps may want to take advantage of SNAPSHOTs where features or bug fixes are available

**Comment by clockfly** [comment]
The snapshot build is pushed to sonatype for every trunk merge.
Check https://oss.sonatype.org/content/repositories/snapshots/com/github/intel-hadoop/gearpump-core_2.11/0.4.1-SNAPSHOT/
