### ISSUE TITLE
Resource should be extensible 

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#151]
Currently when AppMaster is requesting resources it provides a Resource class

```
case class Resource(slots : Int)
case class ResourceRequest(resource: Resource,  workerId: Int = 0, priority: Priority = NORMAL, relaxation: Relaxation = ANY)
```

However Master and related schedulers may need specific information within the Resource such as SLA, capacity, vmcores, etc. Because schedulers are configurable they should be able to receive Resource parameterized by specific resource information. This will also ease any integration or coexistence within  YARN.

**Comment by clockfly** [comment]
We can reopen this when the requirement is solid and clear.
