### ISSUE TITLE
Better support TaskActor.onNext() with similar functionality like ActorContext.become()

### ISSUE THREAD

**Issue by whjiang** [intel-hadoop/gearpump#209]
Currently, the user defined TaskActor.onNext() is the main hook user can used to handle message. However, it is not very convinent when user TaskActor needs to handle state machine. if we can support some lightweight ActorContext.become() like support for TaskActor.onNext(). This makes user coding much easie when handling state machine.

**Comment by clockfly** [comment]
User can define child actor which have state machines.

No sure how or whether it is possible to support state machine directly in TaskActor.
Please reopen this if you have clear proposal.
