### ISSUE TITLE
Define UI Dashboard structure

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#269]
Sub task of master #11 
Provide the dashboard framework which should support an extensible set of widgets that can be added to the dashboard. The dashboard should also support tabs - where each tab will expose the widgets relevant to that tab. The dashboard framework should allow realtime data to be streamed within a given widget. Angular is a good candidate for the framework. D3 is a good candidate for charts. The framework should be served by spray. Best practices should be followed for frontend components. In this case we should use npm, bower, grunt.

**Comment by sirinath** [comment]
Please make the dash board embeddable as well as decoupled from the main implementation so you can replace part of all of in in your applications.

**Comment by clockfly** [comment]
Thanks, @sirinath 

We will decouple the data with UI by rest service.

**Comment by clockfly** [comment]
@kkasravi 

Please work on this branch for UI 
https://github.com/intel-hadoop/gearpump/tree/ui_portal

**Comment by sirinath** [comment]
Something which might be of interest: https://github.com/bpmn-io/diagram-js

**Comment by kkasravi** [comment]
This has been merged into ui_portal branch.
