### ISSUE TITLE
Create a force directed widget

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#270]
subtask of #11 Add more metrics, Graph visualization and UI dashboard
A widget should be created that can fetch the DAG of a given appmaster and display it. This widget should have streaming capabilities so that new data can be displayed as the DAG changes. It should use the REST API to fetch the DAG.

Requirements

- [ ] DAG must allow variety of node types and edges types (arrows, etc).
- [ ] DAG must allow labels over nodes and labels over edges
- [ ] DAG must accept real-time updates which allow it to update nodes and edges
- [ ] DAG should allow easy import/export to xdot or dot
- [ ] DAG should allow interactive editing – to add nodes, edges
- [ ] DAG should allow integration into angular
- [ ] DAG should allow a large number of nodes to be displayed

**Comment by kkasravi** [comment]
Here is an example of a DAG with edges that are labeled

http://jsfiddle.net/bc4um7pc/

**Comment by kkasravi** [comment]
Requirements
- DAG must allow variety of node types and edges types (arrows, etc). 
- DAG must allow labels over nodes and labels over edges
- DAG must accept real-time updates which allow it to update nodes and edges
- DAG must accept real-time updates which allow it to add / remove nodes and edges
- DAG should allow easy import/export to xdot or dot
- DAG should allow easy import/export to a JSON graph structure
- DAG should allow interactive editing – to add nodes, edges
- DAG should allow integration into angular
- DAG should allow a large number of nodes to be displayed

**Comment by stanleyxu2005** [comment]
Added some more candidates:
https://vida.io/documents/WHT5XscEK8enXM983
http://visjs.org/examples/network/29_neighbourhood_highlight.html
http://visjs.org/examples/network/16_dynamic_data.html

**Comment by kkasravi** [comment]
This is an interesting graph+application using d3, dagre, websockets and akka-streams (1.0-M2). https://github.com/timcharper/reactive-viz. Uses spray-websocket from wandoulabs which is what I'm using as well.

**Comment by kkasravi** [comment]
How to add a changeset (new node) to DAG widget
http://www.wenda.io/questions/2929383/dynamically-adding-nodes-to-d3-js-force-directed-graph.html

**Comment by clockfly** [comment]
Take a look at these two:
http://visjs.org/examples/network/17_network_info.html
http://visjs.org/examples/network/31_localization.html

This seems exactly meet what we want, and also it looks beautiful!

**Comment by kkasravi** [comment]
Thanks!, I'll see how they look with complex dag

**Comment by kkasravi** [comment]
Many of these look better than D3 force directed graph and layout well

**Comment by kkasravi** [comment]
This one seems valuable in that the types of layouts seem very relevant (like hubsize)
http://visjs.org/examples/network/32_hierarchicaLayoutMethods.html

**Comment by kkasravi** [comment]
This has been merged into ui_portal branch.
