### ISSUE TITLE
Task order creation should be optimized or AckRequest should be sent from Subscriber to Publisher

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#298]
This is a prerequisite to #167
Currently a DAG is assembled in a topological order using the following code 
```
    val partitioner = new HashPartitioner()
    val c_0 = TaskDescription(classOf[C_0].getName, 1)
    val h_0 = TaskDescription(classOf[H_0].getName, 1)
    val h_1 = TaskDescription(classOf[H_1].getName, 1)
    val h_2 = TaskDescription(classOf[H_2].getName, 1)
    val c_1 = TaskDescription(classOf[C_1].getName, 1)
    val h_3 = TaskDescription(classOf[H_3].getName, 1)
    val h_4 = TaskDescription(classOf[H_4].getName, 1)
    val h_5 = TaskDescription(classOf[H_5].getName, 1)
    val app = AppDescription("dag", classOf[AppMaster].getName, UserConfig.empty, Graph(
      c_0 ~ partitioner ~> h_0,
      c_0 ~ partitioner ~> h_1,
      c_0 ~ partitioner ~> h_2,
      c_0 ~ partitioner ~> c_1,
      c_1 ~ partitioner ~> h_3,
      c_1 ~ partitioner ~> h_4,
      c_1 ~ partitioner ~> h_5
    ))
```
and sent to the AppMaster.  Assuming the graph looks like so

![screen shot 2015-01-13 at 12 44 48 pm](https://cloud.githubusercontent.com/assets/146453/5728841/6bbfff7c-9b22-11e4-8cc2-f1dec0f5507e.png)

The topological order returned is [C_0,H_3,H_0,H_4,H_1,H_5,H_2,C_1]
The task launch order is also [C_0,H_3,H_0,H_4,H_1,H_5,H_2,C_1]

Each TaskActor in it's preStart sends out a first AckRequest to its downstream subscribers. In this case since there are only 2 nodes with downstream subscribers [C_0, C_1], the ordering is of messages from C_0 is:
H_1 ! AckRequest (sender=C_0)
H_0 ! AckRequest (sender=C_0)
H_2 ! AckRequest (sender=C_0)
C_1 ! AckRequest (sender=C_0)
and the ordering of messages from C_1 is:
H_4 ! AckRequest (sender=C_1)
H_5 ! AckRequest (sender=C_1)
H_3 ! AckRequest (sender=C_1)

Ideally we should launch such that the publishers are launched first and that each subscriber makes an AckRequest to each upstream publisher. The net effect would be the same - where each publisher would maintain a set of downstream actors. However it would allow the ReactiveStreams API to be easily implemented - especially when a Subscriber needs to cancel a subscription.

Note: I'm not sure I understand the topological sorting above which was taken from log files.

**Comment by whjiang** [comment]
Hi Kam,

Your topo sort result looks strange to me. How can C_1 be the last tone in sorted result? As H_3, H_4 and H_5 depend on C_1, C_1 definitely shall preceding H_3, H_4, H_5.

**Comment by kkasravi** [comment]
Hi Weihua

The results are from adding LOG.info statements to the code so I'm reasonable sure they are accurate. It's possible that jgrapht has a bug in its topologicalsort...

**Comment by kkasravi** [comment]
Closing this and reactive streams issue #167 for now. Will be addressed on a separate milestone
