### ISSUE TITLE
Allow travis to auto publish signed artifacts to nexus sonatype for snapshot and release builds

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#359]
This is outlined in the article http://blog.eigengo.com/2014/05/25/sbt-and-oss-nexus/#more-5583 and requires the sbt-release plugin.

**Comment by clockfly** [comment]
@kkasravi

To trigger a release build, it has two requisites:
1. You must create a tag on intelhadoop/gearpump,by git command line with condition
2. the version must NOT end with -SNAPSHOT

**Comment by clockfly** [comment]
You can verify whether you can  publish to release build easily before pushing to master.

Here is the steps:
1). Set the env
   ```bash
  export SONATYPE_USERNAME={your user name on sonatype}
  export SONATYPE_PASSWORD={your password on sonatype}
  # any more env you are trying to set
  export PGP_KEY? =
  ```

2). checkout tag 0.2.2 
3). Trying to publish to sonatype release
  ```
  sbt clean publish-signed sonatypeRelease
  ```
If step3 prompt something(like passphrase, or UI) for you to enter, it means the we need to change Build.scala
4). Add necessary changes to Build.scala, and try step 3 again, until step 3 can successfully publish the release package to sonatype release repo.

**Comment by kkasravi** [comment]
The problem is the secret key is accessible on my machine but not Travis, there is a way to do a 'Travis encrypt-file .,.' And point sbt-pgp to this file after extracting it. Right now it's complaining about not finding the secret key on Travis but works fine on my machine.

**Comment by kkasravi** [comment]
I've opened https://github.com/sbt/sbt-pgp/issues/71 indicating the failure.

**Comment by clockfly** [comment]
Have you tried using a clean virtual machine to test this locally, without pushing to travis?

Pgp may look up the default key in home directory.

To do the test in virtual machine, We need to make sure:
/home/travis/build/intel-hadoop/gearpump/secring.asc exist in virtual machine.
SONATYPE_USERNAME is set
SONATYPE_PASSWORD is set

Then if
  sbt clean publish-signed sonatypeRelease
works without asking user to enter anything, then it means your change to Build.scala works, and sbt-pgp works. If there are still problems, then we need to check the travis.yml again.

**Comment by kkasravi** [comment]
what SONATYPE_USERNAME and SONATYPE_PASSWORD are we using?

**Comment by clockfly** [comment]
It is the sonatype website userid and password.

You can use your username/password.
