### ISSUE TITLE
refactor the streaming appmaster 

### ISSUE THREAD

**Issue by clockfly** [intel-hadoop/gearpump#370]
There are several problems currently:

1. MasterHA is not transparent to appmaster. AppMaster need to retry connection to connect to active master.
2. There are a lot of boilplate code which provision the jar to remote node, and start an actor system. 
3. The AppMaster is too big, and not easy to test.

**Comment by manuzhang** [comment]
actually, I'm quite confused with `ApplicationMaster`, `AppMaster`, `AbstractAppMaster`, `AppMasterDaemon`  and what they do

**Comment by clockfly** [comment]
```
actually, I'm quite confused with ApplicationMaster, AppMaster, AbstractAppMaster, AppMasterDaemon and what they do
```

@manuzhang 
AppMasterDaemon will be renamed as AppMasterContainer, actually AppMaster will be started under AppMasterContainer. 
streaming.AppMaster is the AppMaster for streaming application.
core.ApplicationMaster is the interface which need to be extended by any applicaiton master written 
 user.
AbstractAppMaster is not from the core or streaming. It is a from a test module distributedshell.

**Comment by manuzhang** [comment]
Yes, I can more or less understand what they do after reading the code. I feel really confused when I look at the name. `AppMaster` and `ApplicationMaster` just tell me, a user,  the same thing.

**Comment by whjiang** [comment]
According to Sean's feedback, I will suggest following:
1. rename streaming.AppMaster to streaming.StreamingAppMaster
2. rename distrubtedshell.AbstractAppmaster to some more specific name instead of so general one.

**Comment by kkasravi** [comment]
Maybe ShellController

**Comment by whjiang** [comment]
There is a AppMaster in distributedshell. Maybe better to rename it as ShellController or ShellAppMaster is good.
@huafengw why there is an AbstractAppMaster? The only derived class I can find is distributedshell.AppMaster.
