### ISSUE TITLE
KafkaSource.pull is slow due to immutable.List.append

### ISSUE THREAD

**Issue by manuzhang** [intel-hadoop/gearpump#377]
We've observed that pulling from kafka is quite slow. In the current implementation, KafkaConsumer  running in a separate thread will pull in messages from kafka and put on a in memory queue (`LinkedBlockingQueue`), and KafkaSource.pull will continuously poll the head of the queue.  I found that KafkaConsumer pulls at high speed while consume blocks at KafkaSource.pull (below). 

```scala
  override def pull(number: Int): List[Message] = {
    @annotation.tailrec
    def pullHelper(count: Int, msgList: List[Message]): List[Message] = {
      if (count >= number) {
        msgList
      } else {
        val optMsg: Option[Message] = fetchThread.poll.flatMap { kafkaMsg =>
          val msg = messageDecoder.fromBytes(kafkaMsg.msg)
          offsetManagers(kafkaMsg.topicAndPartition).filter(msg -> kafkaMsg.offset)
        }
        optMsg match {
          case Some(msg) => pullHelper(count + 1, msgList :+ msg)
          case None      => pullHelper(count + 1, msgList)
        }
      }
    }
    pullHelper(0, List.empty[Message])
  }
```

As per http://docs.scala-lang.org/overviews/collections/performance-characteristics.html, `immutable.List.append` is linear. Also, I've written a microbenchmark which showed that even using prepand O(1) and then reverse the list would be 7x faster.

**Comment by clockfly** [comment]
For the note, List append operation need to traverse the whole list.
