### ISSUE TITLE
"DAG" with cycle could fail

### ISSUE THREAD

**Issue by manuzhang** [intel-hadoop/gearpump#383]
We use TopologicalOrderIterator to build a DAG but as per the comments in [TopologicalOrderIterator](https://github.com/jgrapht/jgrapht/blob/master/jgrapht-core/src/main/java/org/jgrapht/traverse/TopologicalOrderIterator.java),

> For this iterator to work correctly the graph must be acyclic, and must not be modified during iteration. Currently there are no means to ensure that, nor to fail-fast; the results with cyclic input (including self-loops) or concurrent modifications are undefined. To precheck a graph for cycles, consider using CycleDetector or StrongConnectivityInspector.

As we don't precheck for cycles, user job could fail when they submit a "DAG" with cycle.

**Comment by clockfly** [comment]
Cycle not supported.
