### ISSUE TITLE
ActorSystemBooter process is not shut down after application finishes

### ISSUE THREAD

**Issue by manuzhang** [intel-hadoop/gearpump#394]
The actor system is shut down but the containing process lives.

**Comment by manuzhang** [comment]
verified this happens only on Linux so ActorSystemBooter process gets shut down on Windows

**Comment by clockfly** [comment]
@manuzhang 

Please fix this

**Comment by manuzhang** [comment]
haven't got a clue. This is not reproducible on my ubuntu 14.04 so it could be OS dependent.

**Comment by clockfly** [comment]
Do you have logs when this problem happen?

It should be helpful when trying to identifying the root cause.

**Comment by manuzhang** [comment]
the issue still exists if we use an async kafka producer to persist offsets
