### ISSUE TITLE
bump up kafka version to 0.8.2.0

### ISSUE THREAD

**Issue by manuzhang** [intel-hadoop/gearpump#396]
Kafka has just [released 0.8.2.0](https://archive.apache.org/dist/kafka/0.8.2.0/RELEASE_NOTES.html).

major features, improvements, fixes,

 - A new Java producer for ease of implementation and enhanced performance.
 - A Kafka-based offset storage.
 - Delete topic support.
 - Per topic configuration of preference for consistency over availability.
 - Scala 2.11 support and dropping support for Scala 2.8.
 - LZ4 Compression.

**Comment by clockfly** [comment]
+1, please make a PR.
