### ISSUE TITLE
refactor taskmanager

### ISSUE THREAD

**Issue by clockfly** [intel-hadoop/gearpump#402]
The goal of refactory:

1. Handling zombie executors and tasks. 
2. When there are multiple failures happening at the same time, should handle them gracefully. For example, a executor(jvm) die may trigger multiple MessageLoss exception, the TaskManager should handle this so that we don't restart the application for multiple times.
3. Using FSM instead of become/unbecome so that we minimize the shared data.
4. Make code ut friendly.

**Comment by kkasravi** [comment]
+1 on FSM.
