### ISSUE TITLE
Kafka data source performance report.

### ISSUE THREAD

**Issue by clockfly** [intel-hadoop/gearpump#421]
We need to have a report about how gearpump perform when using kafka as data source.

**Comment by manuzhang** [comment]
I've written up a test report at https://docs.google.com/document/d/19YY_PxBArF9i8LLjMCaU0vKlNchB-IDMe3yos1Q8rw4/edit?usp=sharing

**Comment by clockfly** [comment]
I like the report, thanks!

Maybe we need to post a link to wiki.
