### ISSUE TITLE
Use application name as unique identifier for an application

### ISSUE THREAD

**Issue by huafengw** [intel-hadoop/gearpump#430]

**Comment by clockfly** [comment]
Should:

1. check whether there are application name duplication. 
2. use the application name when storing offest to kafka.

**Comment by huafengw** [comment]
For the second part, now property appname is not available to the TaskActor, is it OK to put this into TaskContext?

**Comment by kkasravi** [comment]
we may also need a unique task identifier for visualization purposes (DAG)
