### ISSUE TITLE
Create standalone build.sbt for examples/ and experiments/ module

### ISSUE THREAD

**Issue by clockfly** [intel-hadoop/gearpump#432]
So that we don't pollute the core Build.scala under root project.

**Comment by clockfly** [comment]
Huafeng,

Please take a look at this.

**Comment by huafengw** [comment]
"You cannot have a project subdirectory or project/*.scala files in the sub-projects. foo/project/Build.scala would be ignored. "
[http://www.scala-sbt.org/release/tutorial/Multi-Project.html]
So for now there is no proper solution to create a standalone Build.scala for experiments and also still can be built from gearpump's Build.scala
