### ISSUE TITLE
kafka producer is not closed in kafka storage

### ISSUE THREAD

**Issue by manuzhang** [intel-hadoop/gearpump#437]
kafka producer may manage a single thread and failure to close the producer will leak resources

**Comment by manuzhang** [comment]
@clockfly I haven't found a better way than adding a `close` method to `TimeReplayableSource`. What do you think ?

**Comment by clockfly** [comment]
Then, add the close(), I think.,

**Comment by clockfly** [comment]
@manu, is this fixed?

**Comment by manuzhang** [comment]
fixed in #470
