### ISSUE TITLE
Branch ui-portal is failed to build

### ISSUE THREAD

**Issue by stanleyxu2005** [intel-hadoop/gearpump#441]
I noticed that some libs are introduced from com.wandoulabs.akka. It seems the current build is failed.
https://travis-ci.org/intel-hadoop/gearpump/builds/50321797

**Comment by kkasravi** [comment]
Thanks Stanley, I'll get to it sometime today

**Comment by clockfly** [comment]
Seems this is fixed in UI branch. 

close this.
