### ISSUE TITLE
Create a widget to show visjs graph

### ISSUE THREAD

**Issue by stanleyxu2005** [intel-hadoop/gearpump#456]
Create an angular widget to show dag-graph using visjs
Requirements:

- [ ] DAG must allow variety of node types and edges types (arrows, etc).
- [x] DAG must allow labels over nodes and labels over edges
- [ ] DAG should allow sparklines over edges which can be clicked on to show related graphs
![screen shot 2015-02-15 at 11 00 22 am](https://cloud.githubusercontent.com/assets/146453/6204480/e68397b6-b501-11e4-9127-85b079e04423.png)

- [x] DAG must accept real-time updates which allow it to update nodes and edges
- [ ] DAG should allow easy import/export to xdot or dot
- [ ] DAG should allow interactive editing – to add nodes, edges
- [x] DAG should allow integration into angular
- [x] DAG should allow a large number of nodes to be displayed

**Comment by clockfly** [comment]
Link with https://github.com/intel-hadoop/gearpump/issues/491

For dynamic modification of DAG.

**Comment by clockfly** [comment]
This is already done.
