### ISSUE TITLE
TaskDescription should allow a name field.

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#459]
Currently tasks within the DAG UI are shown using their class name. This may be confusing in the DAG if we have the same class actor active on more than one DAG node. We should allow the ability to name tasks - with the default being the class name.

**Comment by kkasravi** [comment]
Sean - please indicate by a '+1' or possible alternative. Thanks.

**Comment by clockfly** [comment]
Hi Kam,

This is fixed in https://github.com/intel-hadoop/gearpump/pull/557/files. We now have a processor Id in the DAG.

**Comment by clockfly** [comment]
(TasClassName + ProcessorId) should be enough to differentiate different processors.

**Comment by kkasravi** [comment]
Great, yes. +1
