### ISSUE TITLE
AppMasterSpec and WorkServiceSpec are failing

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#461]
This is failing in ui_portal branch

**Comment by manuzhang** [comment]
I've seen that from time to time.  Will a larger timeout value help ?

**Comment by kkasravi** [comment]
Sure I could try that. I'll let you know.

**Comment by kkasravi** [comment]
This has been merged into ui_portal. It failed because it was merged while the build was in flight which interrupted the build. I verified the travis build completed successfully in the PR that fixed #285, #464.

**Comment by huafengw** [comment]
This issue still exists, the UT AppMasterSpec."find a new master when lost connection with master" often fail.
