### ISSUE TITLE
When launch a application that is not a streaming type, the frontend could not handle it right.

### ISSUE THREAD

**Issue by huafengw** [intel-hadoop/gearpump#512]
for example, launch the Distributed shell
```bin/gear app -jar examples/gearpump-examples-assembly-0.2.4-SNAPSHOT.jar org.apache.gearpump.examples.distributedshell.DistributedShell -master 127.0.0.1:3000```

**Comment by stanleyxu2005** [comment]
This has been fixed together with #544

**Comment by clockfly** [comment]
close this.
