### ISSUE TITLE
Minimize and uglify javascripts in dashboard

### ISSUE THREAD

**Issue by stanleyxu2005** [intel-hadoop/gearpump#518]
Use [sbt-uglify](https://github.com/sbt/sbt-uglify) to minimize and uglify javascripts in dashboard.

**Comment by clockfly** [comment]
Can the js file in webjar be compressed by sbt-uglify?

If not, I think we may not want to resolve this jira, since most of the network is caused by library js in web jars.

**Comment by stanleyxu2005** [comment]
The idea is to uglify and minimize js/css code partials of the angular application as majorly two files. The benefit is to reduce the number of HTTP requests of loading the dashboard. There are dozen of plugins at https://github.com/sbt/sbt-web. sbt-uglify is one of them.

**Comment by stanleyxu2005** [comment]
Using scalajs #952 and dashing will reduce the number of css and js. So I close this issue.
