### ISSUE TITLE
Appmaster detail should return websocket related request urls

### ISSUE THREAD

**Issue by stanleyxu2005** [intel-hadoop/gearpump#546]
The first metrics enabled version has certain code
```
StreamingService.send(JSON.stringify(["org.apache.gearpump.cluster.MasterToAppMaster.AppMasterMetricsRequest",{appId:parseInt($routeParams.appId)}]));
```
If not all kinds of applications will have this metrics to request, better send possible websocket request urls in the response body of a appmaster call.

**Comment by kkasravi** [comment]
Hi Stanley

I was envisioning a REST call that requests the websocket URL. From there we need to define various websocket protocol requests that will be routed within the WebSocketWorker to the correct receiver. I think we may want to make this REST compatible in case websockets are not available. So the JSON request could contain a field like uri which is used for routing and the WebSocketWorker can use to delegate.

**Comment by clockfly** [comment]
We need to add a new REST API which will return the web socket address when queried.
