### ISSUE TITLE
support type safety of message

### ISSUE THREAD

**Issue by clockfly** [intel-hadoop/gearpump#57]
We should not lose message type information.

**Comment by manuzhang** [comment]
Guys, do you have any new thoughts on this ?

**Comment by kkasravi** [comment]
There is now [Akka Typed](http://doc.akka.io/docs/akka/snapshot/scala/typed.html#typed-scala) which provides behaviors and a protocol between actors. Seems like its much more friendly to isolated testing and less error prone. It may also be more light weight to package, not sure.

**Comment by clockfly** [comment]
We now support type safety in DSL high level API.
Close this.
