### ISSUE TITLE
Failed to retrieve application metrics after running couple of minutes

### ISSUE THREAD

**Issue by stanleyxu2005** [intel-hadoop/gearpump#608]
The rest api `http://localhost:8090/metrics/app/3/app3` won't work after application is running couple of minutes. It will return the following message after a timeout instead.
```
An error occurred: Ask timed out on [Actor[akka://services/user/master#-544276379]] after [15000 ms]
```

**Comment by huafengw** [comment]
I launched a local cluster and started 3 wordcount applications but the dashboard seems work well. How can I reproduce this failure?

**Comment by stanleyxu2005** [comment]
Keep get metrics in a high frequency (e.g. every 1-2 second). I doubt if server side cannot retrieve metrics within 15 seconds, actor will be killed by timeout. This leads to unexpected behaviour.
