### ISSUE TITLE
should we allow sending "Message(Array[Byte])"

### ISSUE THREAD

**Issue by manuzhang** [intel-hadoop/gearpump#620]
`Message` requires its content to be `Serializable` such that the content could be sent over the wire. What if that content is already `Array[Byte]` ? Should we allowing sending `Message(Array[Byte])` ? Or rather, users need to wrap it in a Serializable class which needs configuring in `gear.conf` to use the default serializer ?

**Comment by clockfly** [comment]
Definitely, we should.

**Comment by manuzhang** [comment]
we allow sending `AnyRef` now
