### ISSUE TITLE
Cannot delete/kill an application in the UI

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#679]
Because the UI is access via the YARN proxy, attempting to send a DELETE request results in a 405 (DELETE method not allowed). An option would be to send DELETE via web sockets. This means we would need to formalize a websocket protocol that for example sent a JSON structure like
```
{
"operation": "DELETE",
"uri": "/api/v1.0/appmaster/2"
"body":{}
}
```

**Comment by clockfly** [comment]
I don't think we should compromise the REST api design just because the YARN web proxy don't support "DELETE".

What do think about make a redirection with javascript?

**Comment by clockfly** [comment]
For the work around, we can use the command line tool.

Check http://www.gearpump.io/site/0.3/commandlinesyntax/#gear-kill

**Comment by kkasravi** [comment]
Yes, this will work as a work around. The problem with redirection is that the YARN use case (where there is a gateway proxy in front of the master UI) may be common. I do think we should have a WS protocol that can replace the REST one but have parity with functionality.

**Comment by stanleyxu2005** [comment]
Eventually there is a solution with adding an extra line into response header.
```
path("ping"){
      get{
        respondWithMediaType(application/json){
          respondWithHeader(RawHeader("Access-Control-Allow-Origin","*")){
            complete{
                jsonPrefix + """{"result": "PONG"}"""
            }
          }
        }
      }
    }
```

**Comment by kkasravi** [comment]
I know that allows cross site scripting, but does it allow DELETE

**Comment by clockfly** [comment]
This is YARN web proxy limitation, not Gearpump limitation. Close this.
