### ISSUE TITLE
Pipeline: Create HBase tables, columns or assume they are precreated and return appropriate error info to AppMaster

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#687]
Parent task: #400 Kafka -> HBase pipeline

It would be nice if this were defined in the pipeline.conf

**Comment by whjiang** [comment]
I will prefer to assume HBase tables are pre-created.

**Comment by kkasravi** [comment]
Agreed, given the limited time we cannot add too many features above and beyond what is shown in the demo.

**Comment by kkasravi** [comment]
Closed by #400
