### ISSUE TITLE
Build should support cross compile of hadoop distros

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#698]
Right now we have a mix of pure hadoop versions and some cloudera version.
The opportunities to have version mismatches is high.
We should support hortonworks, cloudera, etc as well as pure apache open source.

Runtime should also be able to target different distro's - for example when setting 
classpath and other environment variables for the executors.

**Comment by clockfly** [comment]
We will move hadoop dependency out of core.
