### ISSUE TITLE
DAG processor name is "undefined" if "description` field of TaskDescription is not defined 

### ISSUE THREAD

**Issue by manuzhang** [intel-hadoop/gearpump#704]
Could we fall back to old behavior where class name is used as the displayed processor name on Dashboard if "description" is not defined (e.g. in existing applications) ?

**Comment by kkasravi** [comment]
+1 on the idea of using class name

**Comment by clockfly** [comment]
PR https://github.com/intel-hadoop/gearpump/pull/707
