### ISSUE TITLE
Failure to load any Task results in failure of the entire DAG 

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#709]
In the kafka -> hbase use case (see #400) failure to load the CpuPersistor or MemoryPersistor causes the entire DAG setup to fail. Many messages related to Task.onStart should not be called more than once. @stanleyxu2005, @whjiang @clockfly  We should provide feedback in the UI where a particular DAG node has a big 'X' over it...

**Comment by stanleyxu2005** [comment]
@kkasravi I've provided a PR to fix the UI failure. Could you verify with the Hbase use case?
