### ISSUE TITLE
kafka seems to intermittently fail when connecting to zookeeper and reverts to 127.0.0.1

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#712]
Log is below from executor0.log

[INFO] [03/29/2015 19:48:56.637] [ClientCnxn] EventThread shut down
[WARN] [03/29/2015 19:48:56.648] [ProducerConfig] The configuration value.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer was supplied but isn't a known config.
[WARN] [03/29/2015 19:48:56.648] [ProducerConfig] The configuration key.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer was supplied but isn't a known config.
[INFO] [03/29/2015 19:48:56.648] [KafkaUtil$] ZOOKEEPER CONNECTION 10.10.10.8:2181,10.10.10.96:2181,10.10.10.117:2181/kafka
[INFO] [03/29/2015 19:48:56.649] [ZooKeeper] Initiating client connection, connectString=10.10.10.8:2181,10.10.10.96:2181,10.10.10.117:2181/kafka sessionTimeout=30000 watcher=org.I0Itec.zkclient.ZkClient@7f8a9400
[INFO] [03/29/2015 19:48:56.649] [ZkEventThread] Starting ZkClient event thread.
[INFO] [03/29/2015 19:48:56.649] [ClientCnxn] Opening socket connection to server 10.10.10.117/10.10.10.117:2181. Will not attempt to authenticate using SASL (unknown error)
[INFO] [03/29/2015 19:48:56.650] [ClientCnxn] Socket connection established to 10.10.10.117/10.10.10.117:2181, initiating session
[INFO] [03/29/2015 19:48:56.652] [ClientCnxn] Session establishment complete on server 10.10.10.117/10.10.10.117:2181, sessionid = 0x14c5bf195ce11d7, negotiated timeout = 30000
[INFO] [03/29/2015 19:48:56.653] [ZkClient] zookeeper state changed (SyncConnected)
[INFO] [03/29/2015 19:48:56.681] [ZkEventThread] Terminate ZkClient event thread.
[INFO] [03/29/2015 19:48:56.685] [ZooKeeper] Session: 0x14c5bf195ce11d7 closed
[INFO] [03/29/2015 19:48:56.685] [ClientCnxn] EventThread shut down
[INFO] [03/29/2015 19:48:56.746] [KafkaSource] assigned Set([demogate,0], [demogate,2])
[INFO] [03/29/2015 19:48:56.746] [KafkaProducer@app1exec0TaskId(0,0)] start time is 0
[INFO] [03/29/2015 19:48:57.501] [ClientCnxn] Opening socket connection to server 127.0.0.1/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN] [03/29/2015 19:48:57.502] [ClientCnxn] Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[WARN] [03/29/2015 19:48:57.602] [RecoverableZooKeeper] Possibly transient ZooKeeper, quorum=127.0.0.1:2181, exception=org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/hbaseid
[INFO] [03/29/2015 19:48:57.603] [RetryCounter] Sleeping 2000ms before retry #1...
[INFO] [03/29/2015 19:48:58.603] [ClientCnxn] Opening socket connection to server 127.0.0.1/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN] [03/29/2015 19:48:58.603] [ClientCnxn] Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect

**Comment by manuzhang** [comment]
Hi Kam, I'm afraid that's hbase who failed to connect zookeeper

**Comment by kkasravi** [comment]
yes, i'll close
