### ISSUE TITLE
Pipeline: add data generator to pipeline example 

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#724]
parent task #400 Kafka -> HBase pipeline

This use case needs to be able to generate data into a topic that is subsequently read by pipeline as par t of the kafka -> hbase data flow.

**Comment by manuzhang** [comment]
@kkasravi, one thing I'm not sure is what `on` means in `case class Envelope(id: String, on: String, body: String)` ? Is random string ok for this field ?

**Comment by clockfly** [comment]
Long time not upated. Close this.
