### ISSUE TITLE
Gearpump performance verification with storm-benchmark set

### ISSUE THREAD

**Issue by manuzhang** [intel-hadoop/gearpump#727]
Here is a [report](https://docs.google.com/document/d/1X7ngH0TzIXbENT2EEXdWTftBwmt4271hl5E2RyUV4ec/edit?usp=sharing) for initial results.

**Comment by manuzhang** [comment]
I've corrected the throughput of Gearpump, to be aligned with Storm.

**Comment by manuzhang** [comment]
A short summary 

metrics | throughput (messages/s) | latency (ms)
----------|---------------| ----------
Gearpump | 1,800,000 | 70 
Storm (acker on) | 2,000,000 | 20
Storm (acker off) | 250,000 | -

**Comment by clockfly** [comment]
What is the comparison by running SOL example inside Gearpump-examples?

**Comment by manuzhang** [comment]
I'd say no significant difference. Here's the dashboard snapshot of running Gearpump SOL examples with the same topology configurations.

![](https://lh3.googleusercontent.com/QZ4_1w3ep3XEDIyVVPYjlYJtwnVl7vLRUvELpCZI7SU=w417-h207-p-no)

**Comment by clockfly** [comment]
Here is the updated report.

Closing this issue.
