### ISSUE TITLE
The term "Total processed messages" is confusing

### ISSUE THREAD

**Issue by stanleyxu2005** [intel-hadoop/gearpump#732]
Suggest to change the chart/value in dashboard as four metrics:
1. total received messages (from processors without any outputs)
2. total sent messages (from processors without any inputs)
3. average processor send throughput
4. average processor receive throughput

**Comment by whjiang** [comment]
1. suggest to rename as "Total output messages"
2. suggest to rename as "Total received messages"

Is there any way to show the average latency for message overall handling? I mean, treating the DAG as a blackbox and show the average latency for each message from in to out of this black box.
