### ISSUE TITLE
The fat kafka-hbase pipeline project assembled some unnecessary libraries

### ISSUE THREAD

**Issue by clockfly** [intel-hadoop/gearpump#761]
The fat jar size is over 57MB.

I have seen akka, spray, upickle, and tens of other dependencies included in this fat jar. As the akka is already in the lib, I think we don't need to pack them in this fat jar.

**Comment by kkasravi** [comment]
I'm having some problems on the assembly task with "provided". I think a new version of sbt-assembly corrects some of these issues. I'll work on this. BTW sbt dependencySvg builds a nice visual dependency tree.
