### ISSUE TITLE
ProcessorDescription.description not in TaskContext

### ISSUE THREAD

**Issue by manuzhang** [intel-hadoop/gearpump#767]
When launching a task now, we pass in fields of `ProcessorDescription` except for "description"

```scala
   val taskContext = TaskContextData(taskId, executorId, appId, appName, appMaster = appMaster, taskDescription.parallelism, subscriptions)
   executor ! LaunchTask(taskId, taskContext, TaskUtil.loadClass(taskDescription.taskClass), classOf[TaskActor], taskDescription.taskConf)
```

Here is the definition of `ProcessorDescription`

```scala
case class ProcessorDescription(taskClass: String, parallelism : Int, description: String = "", taskConf: UserConfig = null) extends ReferenceEqual
```

Why do we leave out "description" ? It looks no so useful but StormProducer/StormProcessor could set "description" to the id of the corresponding Storm Spout/Bolt and thus know which component it should execute.  That would solve the unstable topology sort issue (#759), where Storm components construct their own graph to map processor id to component id.

**Comment by clockfly** [comment]
Is this still a issue?
Otherwise, we may close it.
