### ISSUE TITLE
show unified configurations on dashboard

### ISSUE THREAD

**Issue by manuzhang** [intel-hadoop/gearpump#801]
Configs are now read from multiple places (reference.conf under core, reference.conf under application project, gear.conf, application.conf, java properties) with precedence. We need to provide a unified view of config on dashboard such that users could check whether their configuration actually effect. We could have a read-only version now and allow users to modify configurations on dashboard in the future.

**Comment by clockfly** [comment]
Already Resolved by https://github.com/intel-hadoop/gearpump/pull/792/files

**Comment by clockfly** [comment]
The backend is now ready.
