### ISSUE TITLE
[DAG] add alias to represent a DAG

### ISSUE THREAD

**Issue by clockfly** [intel-hadoop/gearpump#821]
Currently, the DAG api is like this:

Graph(a ~ partitioner ~> b,)
Some user complain this is not very convenient to write, we should probably support syntax like this:

Graph(a % partitioner -> b)
That looks simpler.

**Comment by clockfly** [comment]
However, by scala operator precedence rule:

**Comment by clockfly** [comment]
However, by scala precendence rule:
```
|
^
&
< >
= !
:
+ -
* / %
(all other special characters)
```

To be able to left combine, we are not able to use a % b -> c % d -> e, as it will be translated to 
a % (b -> c) % (d->e)

**Comment by clockfly** [comment]
We also cannot use "#" as this char is reserved.

## cannot be used also, as ## is a alias name for function hashCode which exist on every object.

**Comment by clockfly** [comment]
The partitioner and processor must use operator on same precedence level, several options:

a + partitioner -> b + partition2 -> c         (use + , -)
a ~ partitioner ~> b ~ partitioner2 ~> c (current way)
a % partitioner /-> b % partitioner2 /-> c
a @ partitioner ~> b @ partitioner2 ~> c
a $ partitioner ~> b $ partitioner ~> c

**Comment by clockfly** [comment]
"->" is reserved for generating a tuple, in ArrowAssoc.

**Comment by whjiang** [comment]
after discussion with Huafeng and Sean, we prefer to kep current 
a ~ partitioner ~> b 
syntax.

But, we will add a default partitioner for an application. So that, we can use syntax
a ~> b ~> c

**Comment by kkasravi** [comment]
This is the set of operators scala-graph uses - http://www.scala-graph.org/guides/core-initializing.html
