### ISSUE TITLE
The application clock can barely move on when lots of tasks launched in one executor

### ISSUE THREAD

**Issue by huafengw** [intel-hadoop/gearpump#822]
When running SOL in cluster with 1200 tasks and 60 executors, the application clock can not move on.

**Comment by clockfly** [comment]
This is due to upstream akka bug
https://github.com/intel-hadoop/gearpump/issues/898

Now, we have a work-around in https://github.com/intel-hadoop/gearpump/issues/898 which will solve this problem.

mark this as fixed and closed.
