### ISSUE TITLE
Cannot transfer AnyVal in Message

### ISSUE THREAD

**Issue by manuzhang** [intel-hadoop/gearpump#836]
```scala
case class Message(msg: AnyRef, timestamp: TimeStamp = Message.noTimeStamp)
```

Message requires `AnyRef` which excludes all `AnyVal` types (e.g. Short, Int, Long)

**Comment by clockfly** [comment]
Current work around is to box it.

**Comment by clockfly** [comment]
The major difficulty is that kryo need to know the class name to serialize the Message.
```
writeClassAndObject()
```

**Comment by manuzhang** [comment]
the boxed type is `AnyVal`. Currently, I cast it to String.

**Comment by clockfly** [comment]
Maybe you can use java.lang.Integer  to box it explicitly.

That shall work

**Comment by manuzhang** [comment]
what if I don't know whether the data type is `AnyRef` or `AnyVal` ?

**Comment by manuzhang** [comment]
Twitter chill has a [KryoInjection](https://github.com/twitter/chill/blob/develop/chill-bijection/src/main/scala/com/twitter/chill/KryoInjection.scala) that could convert  `Any` to `Array[Byte]`. Maybe there is something we can borrow ?

**Comment by manuzhang** [comment]
superseded by  #1018
