### ISSUE TITLE
Can't put custom user config in application.conf

### ISSUE THREAD

**Issue by jho** [intel-hadoop/gearpump#843]
I get the following exception whenever I try to put some custom configuration in the "application.conf" of the jar that I am submitting to gearpump.  This make's it impossible for me to put any custom configuration that is not related to gearpump in my application.  For now I hack around this by putting a "reference.conf" in my JAR, but this is not an ideal solution. 

[INFO] [04/20/2015 10:16:15.864] [redirect] Exception in thread "main" org.apache.gearpump.cluster.ClusterConfig$ConfigValidationException: Found invalid config section: streamy, we only allow List(gearpump, master, worker, base)
[INFO] [04/20/2015 10:16:15.864] [redirect]     at org.apache.gearpump.cluster.ClusterConfig$$anonfun$validateConfig$2.apply(ClusterConfig.scala:119)
[INFO] [04/20/2015 10:16:15.864] [redirect]     at org.apache.gearpump.cluster.ClusterConfig$$anonfun$validateConfig$2.apply(ClusterConfig.scala:117)
[INFO] [04/20/2015 10:16:15.864] [redirect]     at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[INFO] [04/20/2015 10:16:15.864] [redirect]     at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[INFO] [04/20/2015 10:16:15.864] [redirect]     at scala.collection.mutable.HashSet.foreach(HashSet.scala:79)
[INFO] [04/20/2015 10:16:15.864] [redirect]     at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
[INFO] [04/20/2015 10:16:15.864] [redirect]     at scala.collection.mutable.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:45)
[INFO] [04/20/2015 10:16:15.864] [redirect]     at scala.collection.SetLike$class.map(SetLike.scala:93)
[INFO] [04/20/2015 10:16:15.864] [redirect]     at scala.collection.mutable.AbstractSet.map(Set.scala:45)
[INFO] [04/20/2015 10:16:15.865] [redirect]     at org.apache.gearpump.cluster.ClusterConfig$.validateConfig(ClusterConfig.scala:117)
[INFO] [04/20/2015 10:16:15.865] [redirect]     at org.apache.gearpump.cluster.ClusterConfig$.load(ClusterConfig.scala:96)
[INFO] [04/20/2015 10:16:15.865] [redirect]     at org.apache.gearpump.cluster.ClusterConfig$.load(ClusterConfig.scala:83)
[INFO] [04/20/2015 10:16:15.865] [redirect]     at org.apache.gearpump.util.ActorSystemBooter$.main(ActorSystemBooter.scala:55)
[INFO] [04/20/2015 10:16:15.865] [redirect]     at org.apache.gearpump.util.ActorSystemBooter.main(ActorSystemBooter.scala)

**Comment by clockfly** [comment]
@jho 

Thanks for reporting this, we will fix it.

**Comment by clockfly** [comment]
For the work-around, you can put your config streamy under section gearpump {}

**Comment by clockfly** [comment]
PR:https://github.com/intel-hadoop/gearpump/pull/848

**Comment by clockfly** [comment]
@jho, 

This is fixed in trunk, please check whether it works.

**Comment by clockfly** [comment]
verified with commit https://github.com/intel-hadoop/gearpump/commit/d2a79efc8d49c96fbd00e796b4bfe20721bea322

Please reopen this if you found this problem still exist.
