### ISSUE TITLE
DSL should try and do automatic registration of kryo classes during plan

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#864]
Seems like we know what classes/types will be used during plan execution. Otherwise it becomes very tedious to track down missing classes required for serde especially with opaque kryo messages about class ids.

**Comment by clockfly** [comment]
It is not possible, we only know the top level class. It may contains fields which we don't know.

for example
```
Stream[ClassA]

class ClassA {
  // ClassB also need to be registered explicitly.
  val b: ClassB
}
```

**Comment by whjiang** [comment]
I agree wih @kkasravi that we shall have some auto registration mechanism, though maybe not complete. 

@clockfly raises a good case where total auto registration may be impossible. 

How about this way:
1. at low level API, we provide mechanism for registeration programatically.
2. at DSL, we provide corresponding mechanism for manual registration.
3. at DSL translator, it will check the message types and try to auto register them. If failed, report a translation error and abort translation.

**Comment by kkasravi** [comment]
One possibility is to repeatedly call app.plan.dag catching Serialization exceptions and reporting them although from experience it's very easy to erroneously include a variable that is out of the scope of the method which bubbles up. There is no warning that this is happening. From my understanding - spores will provide warnings and may be worth checking into.

**Comment by clockfly** [comment]
Close this for now, as we don't have a solution yet.
