### ISSUE TITLE
Task onStart should be called after the network transport layer is ready

### ISSUE THREAD

**Issue by clockfly** [intel-hadoop/gearpump#873]
Currently, the TaskActor onStart is called before the netty transport layer is ready. So, if you send message to downstream in onStart, there will be message loss.

**Comment by huafengw** [comment]
This actually causes bug in example transport and stock. If some task try to look up some other task' actor reference for example, the TaskManager is still in StartApplication state, so that the request will fail.

**Comment by clockfly** [comment]
@stanleyxu2005 , Thanks for marking this.

This issue is fixed. 

close this.
