### ISSUE TITLE
UT failure: HistoryMetricsServiceSpec 

### ISSUE THREAD

**Issue by whjiang** [intel-hadoop/gearpump#894]
UT HistoryMetricsServiceSpec will fail:

[info] HistoryMetricsServiceSpec:
[info] SingleValueMetricsStore
[info] - should retain metrics and expire old value *** FAILED ***
[info]   5 did not equal 3 (HistoryMetricsServiceSpec.scala:68)
[info] MinMaxMetricsStore
[info] - should retain min and max metrics data and expire old value
[info] HistogramMetricsStore
[info] - should retain corse-grain history and fine-grain recent data
[info] MeterMetricsStore
[info] - should retain corse-grain history and fine-grain recent data
[info] CounterMetricsStore
[info] - should retain corse-grain history and fine-grain recent data
[info] HistoryMetricsService
[info] - should retain lastest metrics data and allow user to query metrics by path

**Comment by clockfly** [comment]
Not sure whether this is valid anymore. The latest CI is good.

https://travis-ci.org/intel-hadoop/gearpump/builds/70478622
