### ISSUE TITLE
The released TAR package is bad after uncompressing

### ISSUE THREAD

**Issue by haoch** [intel-hadoop/gearpump#905]
I downloaded the tar package from:
[https://github.com/intel-hadoop/gearpump/releases/download/0.3.4/gearpump-pack-0.3.4.tar.gz](https://github.com/intel-hadoop/gearpump/releases/download/0.3.4/gearpump-pack-0.3.4.tar.gz)

When I uncompress it, the file structure seems strange as following, all files are named with full path in front separated with "\" and placed under the root folder instead of child directories:

~~~bash
$ tar xzvf gearpump-pack-0.3.4.tar.gz
x gearpump-pack-0.3.4/bin/
x gearpump-pack-0.3.4/bin\\gear
x gearpump-pack-0.3.4/bin\\gear.bat
x gearpump-pack-0.3.4/bin\\local
x gearpump-pack-0.3.4/bin\\local.bat
x gearpump-pack-0.3.4/bin\\master
x gearpump-pack-0.3.4/bin\\master.bat
x gearpump-pack-0.3.4/bin\\services
x gearpump-pack-0.3.4/bin\\services.bat
x gearpump-pack-0.3.4/bin\\worker
x gearpump-pack-0.3.4/bin\\worker.bat
x gearpump-pack-0.3.4/bin\\yarnclient
x gearpump-pack-0.3.4/bin\\yarnclient.bat
x gearpump-pack-0.3.4/conf/
x gearpump-pack-0.3.4/conf\\gear.conf
x gearpump-pack-0.3.4/conf\\kafka.conf
x gearpump-pack-0.3.4/conf\\log4j.properties
x gearpump-pack-0.3.4/conf\\pipeline.conf.template
x gearpump-pack-0.3.4/conf\\yarn.conf.template
x gearpump-pack-0.3.4/lib/
x gearpump-pack-0.3.4/lib\\activation-1.1.jar
x gearpump-pack-0.3.4/lib\\akka-actor_2.11-2.3.9.jar
x gearpump-pack-0.3.4/lib\\akka-agent_2.11-2.3.6.jar
~~~

My working environment is `Mac OSX 10.10.3 (14D136)`. I guess the problem may be caused because you built the package under windows environment.

**Comment by huafengw** [comment]
@kkasravi Can you help to take a look at this?

**Comment by clockfly** [comment]
@haoch 

It is great to see you here since we last meet:)

The issue is caused by a upstream [sbt-pack bug](https://github.com/xerial/sbt-pack/issues/68) bug, now sbt-pack 0.6.9 has fixed it.

With this bug, when building on windows, the path format in tar package will use backslash "\" instead of "/".

We will sync with upstream fix and push a tag build immediately.

**Comment by clockfly** [comment]
@haoch 

Do you want to make a pull request to upgrade sbt-pack version to 0.6.9? :)

**Comment by haoch** [comment]
Sure, here is the PR #908 :)

**Comment by clockfly** [comment]
I have also updated the download links http://www.gearpump.io/site/downloads/

Now, the 0.3.4 tar.gz is in right-format
