### ISSUE TITLE
clock could rewind on dashboard

### ISSUE THREAD

**Issue by manuzhang** [intel-hadoop/gearpump#907]
The dashboard requests min clock update at certain intervals. During the interval, the clock advances at client clock's pace such that it looks going forward smoothly. This will lead to clock rewind when the application clock advances at a different pace. In extreme cases, what if the application clock pauses for some time ?

**Comment by stanleyxu2005** [comment]
Currently the (display) clock will be synchronized every 10 seconds. And the update interval of appclock is configured as every 2 seconds. 

Here are solutions:
1. Revert back to un-smooth mode. 
2. Not synchronize at fixed rate but when appclock updates. If the appclock is slower than local time delta (now - lastNow), the display clock will be reminded and the UI will splash once as red.
