### ISSUE TITLE
Arrow on DAG graph is gray even with data flowing through

### ISSUE THREAD

**Issue by manuzhang** [intel-hadoop/gearpump#913]
![dag](https://lh3.googleusercontent.com/-Lx3Xt0bnvjY/VVFjVH99DiI/AAAAAAAAD3E/IQerHKk7w7g/w1598-h549-no/Screenshot%2Bfrom%2B2015-05-12%2B10%253A16%253A27.png)

You can tell from the right column that data are flowing through but the arrow on DAG graph is gray which means the opposite.

**Comment by stanleyxu2005** [comment]
Gray means no bandwidth at the moment. It will become normal (blue) when bandwidth > 0.
