### ISSUE TITLE
YARN container failures

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#965]
[Story](https://www.pivotaltracker.com/story/show/95588510)
Handle master and worker container failures

**Comment by clockfly** [comment]
-1

Reason:
1. TaskContext already contains most information of Processor.
2. Some field like taskclass is not useful for Task.
3. Some field will be changed when passing to runtime, like taskConf. It will merge with worker config.
4.  It is risky to serialize user defined Processor and pass them to tasks. As we don't know what fields user may define.
