### ISSUE TITLE
Add additional dashboard definitions

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#984]
[Story](https://www.pivotaltracker.com/story/show/95818676)
[Parent Issue](https://github.com/intel-hadoop/gearpump/issues/952)
Finish defining all top level modules so they can be included in the dashboard module dependencies

**Comment by kkasravi** [comment]
New definitions: AppsCtrl, MasterCtrl, AppDagCtrl

**Comment by clockfly** [comment]
merge into parent issue #952
