### ISSUE TITLE
use external argument parse library

### ISSUE THREAD

**Issue by manuzhang** [intel-hadoop/gearpump#997]
We've found a few issues on argument parse recently and the current codes are quite complicated and error-prone. I'm thinking about using an external argument parse library rather than maintaining our own.

There is already a question on [stackoverflow](http://stackoverflow.com/questions/2315912/scala-best-way-to-parse-command-line-parameters-cli), which provides a bunch of options like Scopt, Argot and Scallop.

**Comment by clockfly** [comment]
Please re-open this when you have a clear proposal.
